version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: cizzors-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: usercizzors
      POSTGRES_DB: cizzors
      
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
