version: '3.1'

services:
  go-app:
    container_name: cizzors-app
    image: cizzor
    build: .
    restart: always
    env_file:
      - .env
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    container_name: cizzors-db
    env_file:
      - .env
      
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
