version: '3.1'

services:
  go-app:
    container_name: cizzors-app
    image: cizzor
    build: .
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    container_name: cizzors-dblocal
    env_file:
      - .env
      
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
